### ISSUE TITLE
Cannot upload build info to artifactory with self signed cert

### ISSUE THREAD

**Issue by IPO-srh-sloan** [JFrogDev/jfrog-cli-go#93] opened 2017-09-05 14:00 UTC
Hi I'm using v1.10.3 of the cli through the VSTS deploy to artifactory task (I've manually downloaded the cli and told the task to use this latest version). I have an artifactory instance with a self signed cert and I've followed the instructions to install the cert in my ~/.jfrog/security folder. This allowed it to upload artifacts. But I still get the following error when it tries to upload build info:
```
Send build information to JFrog Artifactory
PUT https://*****.cloudapp.azure.com/artifactory/api/build with -1-byte payload
System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
Processed: ##vso[task.logissue type=error;]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
PowerShell script completed with 1 errors.
```

**Comment by eyalbe4** [comment] 2017-09-10 16:47
@IPO-srh-sloan,
For troubleshooting purposes, did you try to use JFrog CLI outside VSTS with the self-signed cert configured in the *~/.jfrog/security* directory?
We added to the *dev* branch (which should be eventually merged into the master) an integration test, which tests the self-signed cert functionality. It does that by:
1. Setting up an internal proxy server, from which the test traffic is routed to your Artifactory.
2. Generates a self-signed certificate for the proxy server.
3. Tests the connection.

See the *TestArtifactorySelfSignedCert* function in the [artifactory_test.go](https://github.com/JFrogDev/jfrog-cli-go/blob/dev/jfrog-cli/jfrog/artifactory_test.go) file (in the *dev* branch).

If you're able to clone the code, checkout the dev branch and run the tests (as described in the dev branch [README.md](https://github.com/JFrogDev/jfrog-cli-go/blob/dev/README.md)), this could also provide a hint as to the cause of the issue you're experiencing.

**Comment by eyalbe4** [comment] 2017-10-01 13:56
@IPO-srh-sloan,
Version 1.11.0 includes the *TestArtifactorySelfSignedCert* integration test. Please let us know if the test helps you pinpoint the problem.

**Comment by eyalbe4** [comment] 2017-11-13 14:42
@IPO-srh-sloan,
I'm closing this issue for now. 
Please let us know if you need further assistance with this.

**Closed by eyalbe4** 2017-11-13 14:42 UTC

**Comment by vamsi248** [comment] 2017-12-12 20:05
below are my logs like this....

Starting artifactory...
Found java executable in JAVA_HOME (/docker-java-home/jre)
mkdir: cannot create directory ‘/opt/artifactory/logs/catalina’: Permission denied

** Could not create dir /opt/artifactory/logs/catalina

once i deleted the user lines in the docker then it has taken the root user and container running fine..
why its not giving permission to create that directory in the artifactory user..... any idea...

i need to add anything extra in my dockerfile....

FROM openjdk:8-jre

MAINTAINER xxxxxxxxxxx>

Define environment variables

ENV ARTIFACTORY_HOME=/opt/artifactory
ENV ARTIFACTORY_VERSION=5.4.6
ENV MIN_HEAP_SIZE="-Xms512m"
ENV MAX_HEAP_SIZE="-Xmx2g"

Create artifactory group and user 

RUN groupadd -g 1000 artifactory 
&& useradd -d "$ARTIFACTORY_HOME" -u 1000 -g 1000 -s /sbin/nologin artifactory

Install artifactory

RUN wget "https://api.bintray.com/content/jfrog/artifactory/jfrog-artifactory-oss-${ARTIFACTORY_VERSION}.zip;bt_package=jfrog-artifactory-oss-zip" && 
unzip "jfrog-artifactory-oss-${ARTIFACTORY_VERSION}.zip;bt_package=jfrog-artifactory-oss-zip" && 
mv artifactory-oss-${ARTIFACTORY_VERSION} $ARTIFACTORY_HOME && 
rm "jfrog-artifactory-oss-${ARTIFACTORY_VERSION}.zip;bt_package=jfrog-artifactory-oss-zip"

Define mountable directories

VOLUME $ARTIFACTORY_HOME/data
VOLUME $ARTIFACTORY_HOME/etc
VOLUME $ARTIFACTORY_HOME/logs
VOLUME $ARTIFACTORY_HOME/backup
VOLUME $ARTIFACTORY_HOME/access

Add initialization script

ADD entrypoint.sh /opt/artifactory/bin/entrypoint.sh

Modify script permissions

RUN chmod 755 /opt/artifactory/bin/entrypoint.sh

Change directories ownership to artifactory user and group

RUN chown -R artifactory:artifactory $ARTIFACTORY_HOME

Run the container as artifactory user 

USER artifactory

Define default command

ENTRYPOINT ["/opt/artifactory/bin/entrypoint.sh"]

Expose port

EXPOSE 8081

**Comment by vamsi248** [comment] 2017-12-12 20:05
can anyone has idea
