### ISSUE TITLE
Forbidden response using rt search with api key

### ISSUE THREAD

**Issue by mrpotes** [JFrogDev/jfrog-cli-go#25] opened 2016-10-11 13:23 UTC
I've been experimenting with the CLI, but was unable to get artifactory search to work with the api key. I was trying:

```
bin/jfrog rt s --url https://my.artifactory --apikey abc123def releases/some/path/
```

However, this was returning a `403 Forbidden` response.

I did some experimenting with the REST API, and found that when sending the equivalent HTTP request, I got a response `Only non-anonymous users are allowed to access AQL queries`. Sure enough, when I tried the user and password with the CLI, the query then worked as expected.

Having looked at the REST API docs, I suspect that the following is the correct fix:

```
diff --git a/utils/ioutils/ioutils.go b/utils/ioutils/ioutils.go
index fc1bffa..ccd8f90 100644
--- a/utils/ioutils/ioutils.go
+++ b/utils/ioutils/ioutils.go
@@ -556,7 +556,9 @@ func GetRemoteFileDetails(downloadUrl string, httpClientsDetails HttpClientDetai

 func setAuthentication(req *http.Request, httpClientsDetails HttpClientDetails) {
        //Set authentication
-   if httpClientsDetails.ApiKey != "" {
+ if httpClientsDetails.User != "" && httpClientsDetails.ApiKey != "" {
+         req.SetBasicAuth(httpClientsDetails.User, httpClientsDetails.ApiKey)
+ } else if httpClientsDetails.ApiKey != "" {
                req.Header.Set("X-JFrog-Art-Api", httpClientsDetails.ApiKey)
        } else if httpClientsDetails.User != "" && httpClientsDetails.Password != "" {
                req.SetBasicAuth(httpClientsDetails.User, httpClientsDetails.Password)
```

I have tested this locally, and it appears to work.

**Comment by eyalbe4** [comment] 2016-10-12 05:49
Thanks for reporting and investigating this @mrpotes.
We will check this and update.

**Comment by TamirHadad** [comment] 2016-10-13 10:57
Hi @mrpotes,
I was unable to reproduce this issue.
Can you please check again that your API key is correct?

**Comment by mrpotes** [comment] 2016-10-13 11:06
The API Key was correct.

What aspect have you been unable to reproduce?

**Comment by TamirHadad** [comment] 2016-10-13 11:13
I am doing search using my API key and I am getting the correct search results.

**Comment by mrpotes** [comment] 2016-10-13 11:21
I'm not an admin on my Artifactory, so I can't check the security settings,
but there may be some security enabled in the installation that affects
this? When you send a POST to `[artifactory]/api/search/aql` with header
`X-JFrog-Art-Api` set to your api key, what response do you get? I get 403
with entity `Only non-anonymous users are allowed to access AQL queries`.

I am trying to get admin access so I can check what security settings are.

**Comment by TamirHadad** [comment] 2016-10-13 12:34
What is your Artifactory version? 
I managed to execute a search command using a user with read only permission.

**Comment by mrpotes** [comment] 2016-10-13 13:18
Artifactory Professional
4.2.2 rev 40049

**Comment by TamirHadad** [comment] 2016-10-13 14:16
API key support was added to Artifactory from version 4.3.0.
An API key generated before 4.3.0 can be used instead of a password, this is why your workaround worked.

**Comment by mrpotes** [comment] 2016-10-13 14:33
Right. I see. Does the CLI not support Artifactory 4.2 then?

**Comment by TamirHadad** [comment] 2016-10-13 14:53
We are constantly improving and adding functionality to the CLI in order to allow our users to enjoy Artifactory latest features.
Therefore there might be some features which are not supported with previous versions of Artifactory.
If you are facing any issues due to your Artifactory version you are welcome to report them and we will do our best to address them.

**Comment by mrpotes** [comment] 2016-10-13 14:59
Ok... Feel free to take this as a reported issue against 4.2.2, with a
suggestion for a fix which should be compatible with 4.3+ :)

**Comment by eyalbe4** [comment] 2016-10-26 21:57
@mrpotes, since the existing JFrog CLI functionality is compatible with the recent releases of Artifactory, and supporting both the old and new API Key functionality isn't straight forward, I suggest we close this issue.

**Comment by mrpotes** [comment] 2016-10-27 15:35
I'm surprised to hear you describe this as "isn't straightforward" when the
fix is a simple 2-line change that I've already offered you.

**Comment by eyalbe4** [comment] 2016-10-27 16:07
Hi @mrpotes,
I might have misunderstood your suggestion. How do you suggest we implement this?

**Comment by mrpotes** [comment] 2016-10-27 16:38
The diff in my original comment suggests a fix to ioutils.go - I can raise
as a PR if you prefer?

**Comment by eyalbe4** [comment] 2016-10-27 16:55
Saw it now @mrpotes. Looks like this should work for all Artifactory versions. Sorry for the misunderstanding. No need for a PR. We'll soon test this and commit the code. Thanks!

**Comment by mrpotes** [comment] 2016-10-27 16:57
Great, thought there must have been some miscommunication somewhere - I
should have had the confidence to submit as a PR in the first place (never
touched out read any proper go before) :-)

**Comment by eyalbe4** [comment] 2016-11-02 22:23
@mrpotes, the code has been [committed](https://github.com/JFrogDev/jfrog-cli-go/commit/cdb65b181427c5fba950e202aacf66b82fe2041a) and released as part of version 1.5.1.

**Comment by mrpotes** [comment] 2016-11-04 18:59
Awesome, thanks :-)

**Comment by eyalbe4** [comment] 2016-11-14 09:34
@mrpotes, with your permission, I'm closing this issue.

**Closed by eyalbe4** 2016-11-14 09:34 UTC
