### ISSUE TITLE
jfrog bt upload --override doesn't seem to work

### ISSUE THREAD

**Issue by solvingj** [JFrogDev/jfrog-cli-go#72] opened 2017-07-18 22:51 UTC
Not sure of the possible alternative explanations for the log output below, but currently it appears that the --override=true is not working.  I also tried --override="true" but of course, that did not and should not work. 

```
C:\Users\jerry\jfrog-test>jfrog bt upload --publish=true go-github-release-test.1.0.68.nupkg solvingj/public-choco/go-github-release-test/1.0.68 pool/g/go-github-release-test/
[Info] Verifying repository public-choco exists...
[Info] Verifying package go-github-release-test exists...
[Info] Verifying version 1.0.68 exists...
[Info] [Thread 0] Uploading artifact: go-github-release-test.1.0.68.nupkg
[Debug] [Thread 0] Bintray response: 201 Created
[Info] Uploaded 1 artifacts.

C:\Users\jerry\jfrog-test>jfrog bt upload --override=true --publish=true go-github-release-test.1.0.68.nupkg solvingj/public-choco/go-github-release-test/1.0.68 pool/g/go-github-release-test/
[Info] Verifying repository public-choco exists...
[Info] Verifying package go-github-release-test exists...
[Info] Verifying version 1.0.68 exists...
[Info] [Thread 0] Uploading artifact: go-github-release-test.1.0.68.nupkg
[Debug] [Thread 0] Bintray response: 405 Not Allowed
[Error] [Thread 0] Bintray response: 405 Not Allowed
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

[Info] Uploaded 0 artifacts.
[Error] Failed uploading 1 artifacts.

C:\Users\jerry\jfrog-test>
```

**Comment by eyalbe4** [comment] 2017-07-19 14:30
@solvingJ,
Can you please try using the latest version of JFrog CLI?

**Comment by solvingJ** [comment] 2017-07-19 17:48
Is there something newer than 1.10.1?

```
C:\Users\jerry\jfrog-test>jfrog --version
jfrog version 1.10.1

```

**Comment by eyalbe4** [comment] 2017-07-19 18:37
1.10.1 is currently the latest version.
You can always check it on [Bintray](https://bintray.com/jfrog/jfrog-cli-go).

**Comment by solvingJ** [comment] 2017-07-19 19:34
Here's a fresh example :


```
C:\Users\jerry\jfrog-test>jfrog bt upload --override=true --publish=true go-github-release-test.1.0.68.nupkg solvingj/public-nuget/go-github-release-test/1.0.68 pool/g/go-github-release-test/
[Info] Verifying repository public-nuget exists...
[Info] Verifying package go-github-release-test exists...
[Info] Verifying version 1.0.68 exists...
[Info] Creating version...
[Debug] Bintray response: 201 Created
[Info] Created version 1.0.68.
[Info] [Thread 0] Uploading artifact: go-github-release-test.1.0.68.nupkg
[Debug] [Thread 0] Bintray response: 201 Created
[Info] Uploaded 1 artifacts.

C:\Users\jerry\jfrog-test>jfrog bt upload --override=true --publish=true go-github-release-test.1.0.68.nupkg solvingj/public-nuget/go-github-release-test/1.0.68 pool/g/go-github-release-test/
[Info] Verifying repository public-nuget exists...
[Info] Verifying package go-github-release-test exists...
[Info] Verifying version 1.0.68 exists...
[Info] [Thread 0] Uploading artifact: go-github-release-test.1.0.68.nupkg
[Debug] [Thread 0] Bintray response: 405 Not Allowed
[Error] [Thread 0] Bintray response: 405 Not Allowed
<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

[Info] Uploaded 0 artifacts.
[Error] Failed uploading 1 artifacts.

C:\Users\jerry\jfrog-test>jfrog --version
jfrog version 1.10.1

C:\Users\jerry\jfrog-test>
```

**Comment by solvingj** [comment] 2017-07-21 23:17
@eyalbe4 Is this just me, or are you able to reproduce?

**Comment by eyalbe4** [comment] 2017-07-22 03:08
@solvingj,
We're checking this. We'll let you know what see shortly.

**Comment by eyalbe4** [comment] 2017-07-22 09:31
@solvingj,
It looks like the *override* functionality works well for generic repositories, but overriding an already published nupkg file isn't allowed. I managed to reproduce this.
After I deleted the version from package, I was able to upload and publish the file again.

**Comment by solvingj** [comment] 2017-07-22 13:15
Ok, I will report this as a bug to Bintray.

**Comment by solvingj** [comment] 2017-07-24 23:30
Bintray team confirmed the bug with the API and opened ticket BT-647 in their internal JIRA.

**Comment by solvingj** [comment] 2017-08-25 04:50
FYI, just ran into this bug again.  I just emailed bt support for status.

**Comment by eyalbe4** [comment] 2017-09-13 07:48
@solvingj,
I believe that the override functionality for Nuget repository is now fixed.
Please let us know if the issue is resolved for you.

**Comment by solvingj** [comment] 2017-09-13 14:24
Will do, thanks!

**Comment by eyalbe4** [comment] 2017-10-07 00:53
@solvingj,
I'm closing this issue for now. Please let us know if you need further assistance.

**Closed by eyalbe4** 2017-10-07 00:53 UTC
