### ISSUE TITLE
Artifactory download failing with strconv.ParseInt

### ISSUE THREAD

**Issue by dtothefp** [JFrogDev/jfrog-cli-go#95] opened 2017-09-12 21:46 UTC
I used the jfrog cli to upload to Artifactory 

```
jfrog rt u --build-name=bleep --build-number=10 --server-id=bloop random.bin generic-local/random.bin
```

and then try to download resulting in the error
```
JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt dl generic-local/random.bin random-dl.bin
[Info] Searching items to download...
[Debug] Searching Artifactory using AQL query:
 items.find({"repo": "generic-local","$or": [{"$and": [{"path": {"$match": "."},"name": {"$match": "random.bin"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size","property","type")
[Debug] Artifactory response:  200 OK
[Info] [Thread 2] Downloading generic-local/random.bin
[Error] Artifactory strconv.ParseInt: parsing "": invalid syntax
```

I searched through the code looking for `ParseInt` and tried playing around with the `min-split` option because I thought it was failing in the `cli.go`. Turns out that isn't where it's failing but for some reason setting `--min-split=-1` will successfully download. Any other number for `min-split` results in the above failure

```
# this works!!!

JFROG_CLI_LOG_LEVEL=DEBUG jfrog rt dl --min-split=-1 generic-local/random.bin random-dl.bin
[Info] Searching items to download...
[Debug] Searching Artifactory using AQL query:
 items.find({"repo": "generic-local","$or": [{"$and": [{"path": {"$match": "."},"name": {"$match": "random.bin"}}]}]}).include("name","repo","path","actual_md5","actual_sha1","size","property","type")
[Debug] Artifactory response:  200 OK
[Info] [Thread 2] Downloading generic-local/random.bin
[Debug] [Thread 2]  Artifactory response: 200 OK
[Info] Downloaded 1 artifacts.
```

**Comment by eyalbe4** [comment] 2017-09-13 03:52
Thank you for reporting this issue @dtothefp.
Can you please help us pinpoint the issue by providing us with with the following information?
* Which JFrog CLI version are you using? ```jfrog -v``` prints the version.
* What is the exact size in bytes of the file you're downloading from Artifactory, which causes this error?
* Can you please set the *JFROG_CLI_ERROR_HANDLING* environment variable to *panic* and run the the download command which fails again? With the environment variable set, the CLI should prompt the stack trace, which should help us pinpoint the exact place in the code which fails. Please share with us the command output.

Thanks you

**Comment by dtothefp** [comment] 2017-09-13 17:23
Version: `jfrog version 1.10.3`
File Size: `13791232 Sep 12 14:31 random-dl.bin`

I ran this command (this command works if I do `--min-split=-1`:
```
JFROG_CLI_ERROR_HANDLING=panic jfrog rt dl generic-local/random.bin random-dl.bin
```

 and here is the output:
```
[Info] Searching items to download...
[Info] [Thread 2] Downloading generic-local/random.bin
panic: strconv.ParseInt: parsing "": invalid syntax

goroutine 8 [running]:
github.com/jfrogdev/jfrog-cli-go/utils/cliutils.CheckError(0x18174a0, 0xc42043ae40, 0xa, 0x40)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/utils/cliutils/utils.go:52 +0x83
github.com/jfrogdev/jfrog-cli-go/utils/io/httputils.GetRemoteFileDetails(0xc420422180, 0x51, 0xc420018988, 0x5, 0xc42001a660, 0x1b, 0x0, 0x0, 0xc42043a990, 0xc42044a000, ...)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/utils/io/httputils/http.go:302 +0x16e
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.getFileRemoteDetails(0xc420422180, 0x51, 0xc420144780, 0x0, 0xc42043a960, 0xc42044a000)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/download.go:210 +0xa1
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.isFileAcceptRange(0xc420059a70, 0xc420144780, 0x5, 0xc42001a660, 0x1b)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/download.go:252 +0x4e
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.downloadFile(0xc420059a70, 0xc4201f61d0, 0xb, 0xc420144780, 0xc4201aa000, 0x28)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/download.go:224 +0x407
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.downloadFileIfNeeded(0xc420422180, 0x51, 0x1566ebd, 0x1, 0x7fff5fbff675, 0xd, 0xc4201f61d0, 0xb, 0xc4201f6120, 0xd, ...)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/download.go:390 +0x2f6
github.com/jfrogdev/jfrog-cli-go/artifactory/commands.createFileHandlerFunc.func1.1(0x2, 0xc420039788, 0xc42042fe01)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/artifactory/commands/download.go:370 +0x689
github.com/jfrogdev/jfrog-cli-go/vendor/github.com/gofrog/parallel.(*runner).Run.func1(0xc42042fe50, 0xc42043a210, 0xc42042fe60, 0xc42042fe70, 0x2)
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/vendor/github.com/gofrog/parallel/runner.go:115 +0xaf
created by github.com/jfrogdev/jfrog-cli-go/vendor/github.com/gofrog/parallel.(*runner).Run
        /private/tmp/jfrog-cli-go-20170901-34486-6ciide/jfrog-cli-go-1.10.3/src/github.com/jfrogdev/jfrog-cli-go/vendor/github.com/gofrog/parallel/runner.go:112 +0xd9
```

**Comment by yahavi** [comment] 2017-09-18 13:02
@dtothefp,
Thanks again for reporting this issue.

While investigating this, we found that the error is caused by an attempt to parse a non numeric value returned from Artifactory.

Here are some more details:
In order to determine whether to use bulk or range download from Artifactory, the CLI sends a HEAD request and checks if `Accept-Ranges` is returned as a header in the response. The CLI also checks for other headers such as `Content-Length`. 
In some proxies, like [mitmproxy](https://github.com/mitmproxy/mitmproxy/issues/659), responses to HEAD requests may return without the `Content-Length` header.
Luckily, in Artifactory we already know the file size from the AQL query result, which is sent before the download request. Hence we don't really need the `Content-Length` header which causes the parsing exception.

We will soon release a new CLI version which include a fix for this issue.

**Comment by dtothefp** [comment] 2017-09-18 17:18
@yahavi Thanks for the update. We have Linkerd and HAProxy in front of Artifactory so that header may be omitted by one of those layers. I'm curious why setting `--min-split=-1` results in a successful download?

Please keep in touch with the release that you think will resolve this issue.

**Comment by yahavi** [comment] 2017-09-19 08:31
@dtothefp,
Setting --min-split=-1 forces the CLI to use bulk download. In this case, the CLI doesn't send the mentioned HEAD request.

Here is the link to the commit: https://github.com/JFrogDev/jfrog-cli-go/commit/f5e0451a0ed0f53f1dfc4d237ed7b08c99486914
We will notify you one this fix is released.

**Comment by eyalbe4** [comment] 2017-10-01 13:50
@dtothefp,
1.11.0 has been released and includes this fix.
We'd appreciate your feedback for it.

**Comment by eyalbe4** [comment] 2017-10-18 07:52
@dtothefp,
I'm closing this issue for now. Please let us know if you need further assistance.

**Closed by eyalbe4** 2017-10-18 07:52 UTC
