### ISSUE TITLE
build-add-git errors with ".git: is a directory" message

### ISSUE THREAD

**Issue by giorgio-v** [JFrogDev/jfrog-cli-go#89] opened 2017-08-28 10:01 UTC
When I issue a command like this:
```
/usr/local/bin/jfrog rt build-add-git master 8
```
I get:
```
[Error] read /var/lib/jenkins/workspace/master/.git: is a directory
```
Which is true, of course, but it shouldn’t be an error, correct? 😄 Maybe related to the status of the repo?
```
jenkins@ci-master:~/workspace/master$ git status
HEAD detached at 318d483
nothing to commit, working directory clean
```

**Comment by ortsi** [comment] 2017-08-28 12:49
hi @giorgio-v,
we were unable to reproduce the Error you're receiving, although we a similar git status.

Can you please verify you have the latest CLI version?
also, what happens if you do not leave the .git path empty, but specify the actual path?

we would appreciate some more information to be able to reproduce and debug this.

**Comment by giorgio-v** [comment] 2017-08-28 12:53
My version:
```
admin@ci-master:~$ jfrog --version
jfrog version 1.10.1
```

The behavior is the same without specifying the path.

**Comment by eyalbe4** [comment] 2017-08-28 12:54
@giorgio-v,
Thank you for letting us know about this issue.
We've just pushed [this](https://github.com/JFrogDev/jfrog-cli-go/commit/ca2ff77426dc3abac130de060407814a686cf43c) commit to the *dev* branch. It fixes the issue.

**Comment by giorgio-v** [comment] 2017-08-28 12:54
@eyalbe4 You delete the message I was commenting on. Bad boy. 😆 Anyway, when this commit will become available in the binary release?

**Comment by eyalbe4** [comment] 2017-08-28 13:08
Oops! Sorry about this @giorgio-v!!
We will release a patch version with this fix by the end of the week.
We'll let you know once the patch is released.
Thanks again for reporting this.

**Comment by giorgio-v** [comment] 2017-08-28 13:50
@eyalbe4 Thanks a lot.

**Comment by eyalbe4** [comment] 2017-08-31 15:30
@giorgio-v,
Version 1.10.3 has been released and includes this fix.
We'd appreciate your feedback for it.

**Comment by eyalbe4** [comment] 2017-09-10 16:11
@giorgio-v,
I'm closing this issue for now.

**Closed by eyalbe4** 2017-09-10 16:11 UTC

**Comment by giorgio-v** [comment] 2017-09-11 16:50
It works! Sorry for the delay.

Thanks.  

--
Giorgio Valoti
