### ISSUE TITLE
"build": "BuildJob/LATEST" in spec file gives 415 Unsupported Media Type error

### ISSUE THREAD

**Issue by jlycke** [JFrogDev/jfrog-cli-go#61] opened 2017-06-05 10:59 UTC
https://www.jfrog.com/confluence/display/RTF/Using+File+Specs:
```
{
  "files": [
    {
      "pattern" or "aql": "[Mandatory]",
      "target": "[Mandatory]",
      "props": "[Optional]",
      "recursive": "[Optional, Default: true]",
      "flat": "[Optional, Default: false]",
      "build": "[Optional]"
    }
  ]
}

build
[Optional]
If specified, only artifacts of the specified build are downloaded. The "pattern" property is still taken into account when "build" is specified.
The property format is build-name/build-number.
If the build number is not specified, or the keyword LATEST is used for the build number, then the latest published build number is used.
```

However, using the product structure generic-local/org/prod/version/... (where each version is produced by a separate build) and running the following commands gives 415 Unsupported Media Type error:
```
$ jfrog -version
jfrog version 1.9.0

$ cat bin.spec
{
    "files": [
        {
            "pattern": "generic-local/org/prod/",
            "target": "localdir/",
            "build": "BuildJob/LATEST"
        }
    ]
}

$ jfrog rt dl --spec bin.spec
[Info] Performing SSH authentication...
[Info] SSH authentication successful.
[Info] Searching items to download...
[Error] Artifactory response: 415 Unsupported Media Type
{
  "errors": [
    {
      "status": 415,
      "message": "Unsupported Media Type"
    }
  ]
}
```

Expected/wanted behavior is to fetch all files produced from the latest build of "BuildJob".

Note that specifying a specific version also gives unexpected results. Running:
```
$ cat bin.spec
{
    "files": [
        {
            "pattern": "generic-local/org/prod/",
            "target": "localdir/",
            "build": "BuildJob/123"
        }
    ]
}

$ jfrog rt dl --spec bin.spec
...
...
```
downloads all artifacts below generic-local/org/prod/ but the expected behavior is to only download the artifacts produced from BuildJob/123.

Maybe I misinterpret the documentation and my spec file is incorrect?

**Comment by DimaNevelev** [comment] 2017-06-06 08:52
Thank you @jlycke for reporting this.
We are investigating the "Unsupported Media Type" error.
As for the download behavior, when a build param is provided the CLI will download all the files that have the checksums that were uploaded by the provided build and match the spec pattern. So basically if the same artifact was deployed twice in two separate builds and both will match the pattern, both will be downloaded. Is this your case?

**Comment by DimaNevelev** [comment] 2017-06-06 12:29
We have fixed the "Unsupported Media Type" error. The relevant commit can be viewed [here](https://github.com/JFrogDev/jfrog-cli-go/commit/fc86d9e48f92079e594749d5430add760659951a).
This fix will be added in our next JFrog CLI release.
As a workaround, you can use basic authentication or build the CLI from our dev branch.

**Comment by jlycke** [comment] 2017-06-07 09:07
Thank you @DimaNevelev for the "Unsupported Media Type" fix.

Regarding the download behavior, after double checking the checksum it seems like you are correct. The files that are downloaded several times are the same. However, this is very confusing.

We use the "build.number" as version.

```
generic-local/org/prod/
                      123/
                         files...
                      124/
                         files...
                      125/
                         files...
```

So we basically know that all files in prod/124 origins from BuildJob/124.

With the spec file:
```
{
    "files": [
        {
            "pattern": "generic-local/org/prod/",
            "target": "localdir/",
            "build": "BuildJob/124"
        }
    ]
}
```
we only expect files to be downloaded from "generic-local/org/prod/124/". Seeing files from "generic-local/org/prod/123/" in the log is very worrisome (even though the files are the same).

Note that the behavior for "props" differs. If I specify the properties build.name and build.number with the same pattern then the files are only downloaded once. Shouldn't the behavior with "build" be the same? The problem with using properties is that I can't use the LATEST functionality.

Isn't it also a waste to download the same file several times?

Thank you for the quick response!

**Comment by DimaNevelev** [comment] 2017-06-07 13:50
The functionality should indeed be optimised. We will add a fix for it in one of the CLI's upcoming releases.
Currently, you can achieve this behaviour by providing a more specific path. For example "generic-local/org/prod/124/".

**Comment by eyalbe4** [comment] 2017-10-07 01:25
@jlycke,
Version 1.11.1 includes an improvement to the logic and AQL used for searching artifacts by builds in Artifactory.
We believe that the issue you described should also be resolved by this fix.
We would appreciate your feedback for it. Thank you.

**Comment by eyalbe4** [comment] 2017-11-13 14:44
@jlycke,
With your permission, I'm closing this issue.
Please let us know in case the issue is not resolved.

**Closed by eyalbe4** 2017-11-13 14:44 UTC
