### ISSUE TITLE
No event notification e-mail is being sent on uploading a file with CLI

### ISSUE THREAD

**Issue by cschyma** [JFrogDev/jfrog-cli-go#24] opened 2016-10-04 13:55 UTC
I am using CLI 1.5.0 with server 4.6.1.

Uploading manually via the Web UI works as expected (e-mail received by all user with read permission and watch activated).

**Comment by zanbel** [comment] 2016-10-06 07:54
Hi @cschyma,

I was unable to reproduce this behavior using the same versions provided in your example. Do you see any errors in artifactory log in the process of uploading the file?

**Comment by cschyma** [comment] 2016-10-17 14:04
No error at all. It looks exactly like uploading via the UI.

artifactory.log
`2016-10-17 15:57:44,138 [http-nio-127.0.0.1-8081-exec-240] [INFO ] (o.a.e.UploadServiceImpl:453) - Deploy to 'generic-development:name/app/app-T1.1.20-897.zip' Content-Length: 511227684
2016-10-17 15:58:20,825 [http-nio-127.0.0.1-8081-exec-237] [INFO ] (o.a.e.UploadServiceImpl:453) - Deploy to 'application-development:test.zip' Content-Length: 0`

access.log
`2016-10-17 15:57:20,351 [ACCEPTED LOGIN]  for csym/10.20.16.123.
2016-10-17 15:58:20,876 [ACCEPTED DEPLOY] application-development:test.zip for csym.`

Is there a log for sending e-mails?

**Comment by eyalbe4** [comment] 2016-10-19 11:13
@cschyma, no, there's no logging for that. I suggest you give it a try with a different email address. For further troubleshooting, you can try uploading by using the REST API directly. In case you're still unable to receive emails, you can send an email to support@jfrog.com with all the details and we'll try to assist you from there.

**Comment by cschyma** [comment] 2016-10-31 09:10
Thanks.

I have created a bug report at https://www.jfrog.com/jira/browse/JGC-77 .

**Comment by eyalbe4** [comment] 2016-11-02 22:16
@cschyma,
Since this issue does not reproduce for us, and we want to help you resolve the issue, I suggest you contact our Support Team by sending an email to support@jfrog.com with all the details and we'll try to assist you through that channel.

**Comment by eyalbe4** [comment] 2017-01-01 22:09
@cschyma,
With your permission, I'm closing this issue, since we haven't been able to reproduce it. In case this is still an issue for you, we suggest you contact JFrog Support.

**Closed by eyalbe4** 2017-01-01 22:09 UTC

**Comment by cschyma** [comment] 2017-04-06 09:35
I've been in contact with JFrog Support. The problem was reproducabe on our local system and updating from Artifactory 4.6.1 to 5.0.0 solved it.

Thank you very much!
